name: Create release, upload to Figshare

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'DR*'  # Push events to matching DR*

jobs:
  release-n-upload:
    runs-on: ubuntu-latest
    env:
      STAGE_ARTICLE_ID: 7072554

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # No body: defaults to tag message and body
          draft: false
          prerelease: false
      - name: Upload files to stage instance
        uses: figshare/github-upload-action@v1.1
        with:
          FIGSHARE_TOKEN: ${{ secrets.FIGSHARE_TOKEN }}
          FIGSHARE_ENDPOINT: 'https://api.figsh.com/v2'
          FIGSHARE_ARTICLE_ID: ${{ env.STAGE_ARTICLE_ID }}
          DATA_DIR: 'upload'
      - name: Check on review status
        shell: bash
        env:
          AUTH: "Authorization: token ${{ secrets.FIGSHARE_TOKEN }}"
          URL_STATUS: https://api.figsh.com/v2/account/articles/${{ env.STAGE_ARTICLE_ID }}
          URL_PUBLISH: https://api.figsh.com/v2/account/articles/${{ env.STAGE_ARTICLE_ID }}/publish
        run: |
          fs_status=`curl -X GET -H $AUTH $URL_STATUS | \
          python3 -c "import sys, json; print(json.load(sys.stdin)['curation_status'])"`
          if [[ $fs_status eq 'approved' ]]
          then
            curl -X POST -H $AUTH $URL_PUBLISH
          else
            echo "Deposit under review, not uploading"
          fi
