name: Create release, upload to Figshare

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'DR*'  # Push events to matching DR*

jobs:
  release-n-upload:
    runs-on: ubuntu-latest
    env:
      STAGE_ARTICLE_ID: 7072554

    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          # This token is provided by Actions, you do not need to create your own token
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          # No body: defaults to tag message and body
          draft: false
          prerelease: false
      - name: Check on deposit review status
        shell: bash
        env:
          AUTH: "Authorization: token ${{ secrets.FIGSHARE_TOKEN }}"
          URL: https://api.figsh.com/v2/account/articles/${{ env.STAGE_ARTICLE_ID }}
        run: |
          echo $URL
          echo FS_STATUS<<EOF' >> $GITHUB_ENV
          curl -H $AUTH $URL | \
            python3 -c "import sys, json; print(json.load(sys.stdin)['curation_status'])")" >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
          echo $FS_STATUS
      - name: Upload files to stage instance
        if: ${{ env.FS_STATUS == 'approved' }}
        uses: figshare/github-upload-action@v1.1
        with:
          FIGSHARE_TOKEN: ${{ secrets.FIGSHARE_TOKEN }}
          FIGSHARE_ENDPOINT: 'https://api.figsh.com/v2'
          FIGSHARE_ARTICLE_ID: ${{ env.STAGE_ARTICLE_ID }}
          DATA_DIR: 'upload'
      - name: Submit for publication / curation review
        shell: bash
        env:
          AUTH: "Authorization: token ${{ secrets.FIGSHARE_TOKEN }}"
          URL_PUBLISH: https://api.figsh.com/v2/account/articles/${{ env.STAGE_ARTICLE_ID }}/publish
        run: |
          if [[ $FS_STATUS = 'approved' ]]
          then
            curl -X POST -H $AUTH $URL_PUBLISH
          else
            echo "Deposit under review, not uploading"
            echo "Will need to re-run workflow after current version is published"
          fi
